package Sistema;


import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class MainMenu extends javax.swing.JFrame {
    
     private String user;//Propriedade/variavel necessária para passagem de parametros

    /**
     * Creates new form MainMenu
     * @param user
     */
    public MainMenu(String user) {// add parametros para receber envio de parametro da tela de login
        initComponents();
        this.user = user; // Isto permite assessar a variavel
        
        
        
        //user = login.login(userLogin, senhaLogin, user, senha);
        
            if (this.user.equals("Java")){
                lblStatus.setText("Bem vindo, "+user+"!");
                saldo = saldoJava;
                debito = debitoJava;
                URL url = getClass().getResource("/imgs/java-100px.png");
                Icon icon = new ImageIcon(url);
                lblFotoUser.setIcon(icon);
            }else if (user.equals("Java2")){
                lblStatus.setText("Bem vindo, "+user+"!");
                saldo = saldoJava2;
                debito = debitoJava2;
                URL url = getClass().getResource("/imgs/java2-100px.png");
                Icon icon = new ImageIcon(url);
                lblFotoUser.setIcon(icon);
            } else {
                lblStatus.setText("Faça Login!");
                saldo = 0;
                debito = 0;
            }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBanco = new javax.swing.JLabel();
        btnSaldo = new javax.swing.JButton();
        btndebito = new javax.swing.JButton();
        btnDepos = new javax.swing.JButton();
        btnEmpre = new javax.swing.JButton();
        btnSaque = new javax.swing.JButton();
        btnTransf = new javax.swing.JButton();
        btnQuitarD = new javax.swing.JButton();
        lblFotoUser = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBanco.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblBanco.setText("GUI Bank");
        getContentPane().add(lblBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 102, -1, -1));

        btnSaldo.setText("Consultar Saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 246, 184, 82));

        btndebito.setText("Consultar Débtos");
        btndebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndebitoActionPerformed(evt);
            }
        });
        getContentPane().add(btndebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 246, 184, 82));

        btnDepos.setText("Realizar Depósito");
        btnDepos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeposActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepos, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 339, 184, 82));

        btnEmpre.setText("Realizar Empréstimo");
        btnEmpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpreActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 433, 184, 82));

        btnSaque.setText("Realizar Saque");
        btnSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 340, 184, 80));

        btnTransf.setText("Realizar Transferência");
        btnTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransfActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransf, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 433, 184, 82));

        btnQuitarD.setText("Quitar Débitos");
        btnQuitarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarDActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuitarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 527, 184, 82));

        lblFotoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/usuario-annimo-100px.png"))); // NOI18N
        getContentPane().add(lblFotoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 68, 136, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Faça Login");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 156, 147, 40));

        btnFechar.setText("Sair do App");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 527, 184, 82));

        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 173, -1, -1));

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 173, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        user = "";
        lblStatus.setText("Faça Login");
        URL url = getClass().getResource("/imgs/usuario-annimo-100px.png");
        Icon icon = new ImageIcon(url);
        lblFotoUser.setIcon(icon);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        JFrame janela = new TelaLogin();// add parametro usuario para tela menu. Substituir por classe exixtente
        janela.setVisible(true);
        janela.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
        if (user.equals("Java")){
                saldo = saldoJava;
                saldo = oprs.saldo(saldo);
            }else if (user.equals("Java2")){
                saldo = saldoJava2;
                saldo = oprs.saldo(saldo);
            } else {
                saldo = 0;
                JOptionPane.showMessageDialog(null, "Faça Login");
            }
        
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btndebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndebitoActionPerformed
        // TODO add your handling code here:
        if (user.equals("Java")){
                debito = debitoJava;
                debito = oprs.debito(debito);
            }else if (user.equals("Java2")){
                debito = debitoJava;
                debito = oprs.debito(debito);
            } else {
                saldo = 0;
                JOptionPane.showMessageDialog(null, "Faça Login");
            }
    }//GEN-LAST:event_btndebitoActionPerformed

    private void btnDeposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeposActionPerformed
        // TODO add your handling code here:
        if (user.equals("Java")){
                saldoJava += oprs.depos();
            }else if (user.equals("Java2")){
                saldoJava2 += oprs.depos();
            } else {
                JOptionPane.showMessageDialog(null, "Faça Login");
            }
    }//GEN-LAST:event_btnDeposActionPerformed

    private void btnSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaqueActionPerformed
        // TODO add your handling code here:
        if (user.equals("Java")){
                saldoJava -= oprs.saque();
            }else if (user.equals("Java2")){
                saldoJava2 -= oprs.saque();
            } else {
                JOptionPane.showMessageDialog(null, "Faça Login");
            }
    }//GEN-LAST:event_btnSaqueActionPerformed

    private void btnEmpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpreActionPerformed
        // TODO add your handling code here:
        if (user.equals("Java")){
                addValor = oprs.empre(saldo, empre);
                saldoJava += addValor;
                debitoJava += addValor;
            }else if (user.equals("Java2")){
                addValor = oprs.empre(saldo, empre);
                saldoJava2 += addValor;
                debitoJava2 += addValor;
            } else {
                JOptionPane.showMessageDialog(null, "Faça Login");
            }
    }//GEN-LAST:event_btnEmpreActionPerformed

    private void btnTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransfActionPerformed
        // TODO add your handling code here:
                    if (!user.equals("")){
                            input = JOptionPane.showInputDialog("Digite o valor da transferencia:");
                            valor = Float.parseFloat(input);
                            
                            input = JOptionPane.showInputDialog("Digite o nome do beneficiário( 'Java' ou 'Java2'): ");
                            contaBen = input;
                            
                            if (contaBen.equals(user)){
                                JOptionPane.showMessageDialog(null, "Negado! Não é possível transferir valores para essa mesma conta.");
		
                            }else if (contaBen.equals(userJava)){
                                saldoJava2 -= valor;
                                saldoJava += valor;
                                JOptionPane.showMessageDialog(null, "Transferencia de R$ "+valor+" realizada com sucesso para "+contaBen+"!");
		
                            } else if (contaBen.equals(userJava2)){
                                saldoJava -= valor;
                                saldoJava2 += valor;
                                JOptionPane.showMessageDialog(null, "Transferencia de R$ "+valor+" realizada com sucesso para "+contaBen+"!");
                    
                            } else {
                                JOptionPane.showMessageDialog(null, "Beneficiário inválido!");
                            }
                    }else{
                        JOptionPane.showMessageDialog(null, "Faça Login");
                    }
    }//GEN-LAST:event_btnTransfActionPerformed

    private void btnQuitarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarDActionPerformed
        // TODO add your handling code here:
                try{    
                    if (user.equals("Java")){
                        input = JOptionPane.showInputDialog("Digite o valor da pagamento:");
                        valor = Float.parseFloat(input);
                        saldoJava -= valor;
                        debitoJava -= valor;
                        JOptionPane.showMessageDialog(null, "Pagamento de R$ "+valor+" realizado com sucesso!");
                    }else if (user.equals("Java2")){
                        input = JOptionPane.showInputDialog("Digite o valor da pagamento:");
                        valor = Float.parseFloat(input);
                        saldoJava2 -= valor;
                        debitoJava2 -= valor;
                        JOptionPane.showMessageDialog(null, "Pagamento de R$ "+valor+" realizado com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Faça Login");
                    }
                }catch (NumberFormatException erro){
                    JOptionPane.showMessageDialog(null, "Digite apenas números válidos!");
                }
        
    }//GEN-LAST:event_btnQuitarDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String xuser = "";
                new MainMenu(xuser).setVisible(true);

        
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepos;
    private javax.swing.JButton btnEmpre;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnQuitarD;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSaque;
    private javax.swing.JButton btnTransf;
    private javax.swing.JButton btndebito;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblFotoUser;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

// MINHAS VARIAVEIS
//================== DADOS USUÁRIOS ============================================        
    //Usuário Java
    String userJava = "Java";
    String senhaJava = "abc@123";
    double saldoJava = 0;
    double debitoJava = 0;
    
    //Usuário Java 2
    String userJava2 = "Java2";
    String senhaJava2 = "abc@123j2";
    double saldoJava2 = 0;
    double debitoJava2 = 0;
       
//==============================================================================       
        // VAR AUX LOGIN USUARIOS
        String userLogin = "";
        String senhaLogin = "";
	//String user ="";
	String senha ="";
	int cont = 0;
        
        //VARIAVEIS AUXILIARES
        String input = "";
        double valor = 0;
        String contaBen = "";
        double saldoBen = 0;
        int opc = 0;
        
        // VARIAVEIS AUXILIARES PARA OPERAÇÕES
        double addValor = 0;
        //double addSaldo = 0;
        double saldo = 0;
        double addDebito = 0;
        double debito = 0;
        double depos = 0;
        double empre = 0;
        double saque = 0;
        double trans = 0;
        

        
        
//=================== OBJETOS ==================================================

ClassOperations oprs = new ClassOperations(saldo, debito, depos, empre, saque, trans, userJava, saldoJava, userJava2, saldoJava2);

ClassLogin login = new ClassLogin(userLogin, senhaLogin, user, senha); 

TelaLogin inputLogin = new TelaLogin();




// FIM MINHAS VARIAVEIS
}
