/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaLogin extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public TelaLogin() {
	initComponents();
        //this.userTlogin = userTlogin;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnFechar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("USUÁRIO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 87, -1, -1));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 82, 268, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("SENHA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 133, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clearIcon_50x50.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 241, 68, -1));

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/enterIcon_50x50.png"))); // NOI18N
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 241, 68, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 87, 21, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 133, 21, -1));

        lblError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 178, 268, 23));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 128, 268, -1));

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/closeIcon_50x50.png"))); // NOI18N
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 241, 68, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 500, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
	txtUser.setText("");
	txtSenha.setText("");
	lblError.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
	// Botão logar
	
        /*
        try{
	String senha = "abc@123", usuario = "Java";
	
	String userLogin = txtUser.getText();
	char[] charSenha = txtSenha.getPassword();
	String auxSenha = String.copyValueOf(charSenha);
        
        if(userLogin.equals(usuario)&& auxSenha.equals(senha)){
	    dispose();// Fecha janela de login após login
	    JFrame janela = new MainMenu(userLogin);// add parametro usuario para tela menu. Substituir por classe exixtente
	    janela.setVisible(true);
	    janela.setLocationRelativeTo(null);
	}else{
	    lblError.setText("FALHA NO LOGIN");
	}
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
        */
        
//============================================================

try{
for (int cont=3; cont >0 && cont <4; cont--) {
    String userLogin = txtUser.getText();
    char[] charSenha = txtSenha.getPassword();
    String auxSenha = String.copyValueOf(charSenha);
    String user = "";

        if (userLogin.equals("Java")&& auxSenha.equals("abc@123")){
            cont = 0;
            user = userLogin;
            dispose();// Fecha janela de login após login
	    JFrame janela = new MainMenu(user);// add parametro usuario para tela menu. Substituir por classe exixtente
	    janela.setVisible(true);
	    janela.setLocationRelativeTo(null);
            //JOptionPane.showMessageDialog(null, "Seja bem vindo "+user+"!");
                    		
        }else if (userLogin.equals("Java2")&& auxSenha.equals("abc@123j2")){
            cont = 0;
            user = userLogin;
            dispose();// Fecha janela de login após login
	    JFrame janela = new MainMenu(user);// add parametro usuario para tela menu. Substituir por classe exixtente
	    janela.setVisible(true);
	    janela.setLocationRelativeTo(null);
            //JOptionPane.showMessageDialog(null, "Seja bem vindo "+user+"!");
		
        }else {
            user = "Inválido";
            lblError.setText("FALHA NO LOGIN. USUÁRIO "+user+"!");
            JOptionPane.showMessageDialog(null, "Usuário inválido. Restão "+(cont-1)+" tentativas.");
        }
                        
} // FIM FOR   

}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
//============================================================    
        
	
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
	System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new TelaLogin().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables



}
